user:
  sam:
    username: shenshaotian
    password: shenshaotian

test_url: https://www.test.aiautoex.com

mysql:
  db: amazon_data
  host: rm-wz91136429opn0crwwo.mysql.rds.aliyuncs.com
  password: R40VeJGkg7yE35k
  port: 3306
  user: carving_test